import type { CvLabels } from "@/lib/cv/labels";

export const testLabels: CvLabels = {
  sections: {
    summary: "Resumo",
    experiences: "Experiências",
    skills: "Skills",
    certifications: "Certificações",
    education: "Educação",
    caseStudy: "Case study",
  },
  panelTitle: "Monte o CV",
  customize: "Personalizar",
  close: "fechar",
  selectAll: "marcar todas",
  clearAll: "desmarcar todas",
  download: "Baixar PDF",
  generating: "Gerando…",
  downloadError: "Não foi possível gerar o PDF. Tente novamente.",
  current: "atual",
  validUntil: "válida até",
  caseStudyCta: "case study completo",
  stack: "Stack",
  targeted: "Vaga específica",
  focus: "Destacar tecnologias",
  focusPlaceholder: "Laravel, Angular, PHP",
  focusHint: "Skills que batem vão para a frente e ganham destaque na stack de cada experiência.",
  coreStack: "Stack principal",
  summaryOverride: "Resumo personalizado",
  summaryOverrideHint: "Vazio usa o resumo padrão.",
};
