import type { Experience } from "@/domain";

export const experiences: Experience[] = [
  {
    company: "G4F Soluções Corporativas",
    role: "Full Stack Engineer",
    employmentType: "freelance",
    start: "2022-03",
    end: null,
    location: "Brasília-DF",
    stacks: [
      "Angular 22",
      "Angular Material + Fuse",
      "NestJS 11",
      "Laravel",
      "TypeScript",
      "Next.js 15 (App Router/Turbopack)",
      "React 18",
      "MUI 5",
      "Tailwind CSS",
      "Redux",
      "React Query",
      "SWR",
      "Formik/Yup",
      "Highcharts",
      "i18n (next-intl)",
      "Transloco",
      "ng-apexcharts",
      "Prisma 6",
      "Passport/JWT",
      "NestJS Throttler",
      "WebSockets (socket.io)",
      "Express",
      "AdonisJS",
      "Deno",
      "PostgreSQL",
      "Redis",
      "Docker",
      "Kubernetes",
      "Microservices",
      "gov.br SSO (Login Único/OIDC)",
      "gov.br Design System (GOVBR-DS)",
      "Jest",
      "SonarQube",
      "Jenkins",
      "GitLab CI",
      "hCaptcha + facial biometrics",
      "DOMPurify",
      "Per-request CSP/HSTS",
      "Document generation (PDF/xlsx)",
      "Transactional email (MJML)",
      "Bamboo",
      "Harbor",
    ],
    projects: [
      {
        name: "Large-scale public service system (federal public sector)",
        description:
          "Multi-language citizen-facing platform used across 90+ service units, with document generation and identity verification",
      },
      {
        name: "Next-generation public service system (federal public sector)",
        description:
          "Creation of the modernized version that will replace the legacy system used across all units",
      },
    ],
    highlights: [
      "Founding engineer of the next-generation system: authored the first commit of both the NestJS back end and the Next.js front end, and remain the main contributor to both codebases.",
      "Built the end-to-end service request flow (creation, service bundles, document validation, history) and the real-time service queue and calling screen over WebSocket, with a JWT-authenticated gateway and multilingual text-to-speech.",
      "Led an application security audit and its remediation: central ownership and tenant-scope checks for object-level authorization, default-deny role guards, CSP, rate limiting, upload validation by magic bytes and PII masking in audit logs.",
      "Designed and built the legacy-to-new data migration (MongoDB → PostgreSQL): read-only paged extraction, idempotent and reversible loads with a correlation map and rollback, dry-run mode, validated end to end in a sandbox.",
      "Authored the CI/CD pipeline (Bitbucket Pipelines, SonarQube, Dependency-Track, Docker images on Harbor, Kubernetes deploys to 4 environments) and the local quality gates (Husky, lint-staged, SonarQube pre-push, coverage gate).",
      "Maintain the legacy system in production (Node.js, Express, MongoDB), one instance per unit across 90+ units: a certificate-issuance service with PDF, QR code and public validation, a scheduling race-condition fix, and cursor reconnection with exponential backoff after a production incident.",
      "Spec-driven workflow with specs and plans versioned next to the code, multi-agent orchestration with schema-validated output and adversarial review, and an internal engineering-memory RAG (PostgreSQL + pgvector, hybrid search, knowledge graph) exposed through a custom MCP server.",
    ],
  },
  {
    company: "VegaIT",
    role: "Frontend Developer",
    employmentType: "part-time",
    start: "2022-08",
    end: "2024-05",
    location: "Brazil",
    stacks: [
      "React",
      "Redux",
      "Context API",
      "React Query",
      "TypeScript",
      "MSW",
      "Styled Components",
      "JWT",
      "Azure DevOps (Pipelines)",
      "ESLint/Prettier/tsc",
    ],
    projects: [
      {
        name: "SIM – Maintenance",
        description:
          "Hotel maintenance management: equipment QR codes, floor/room/asset registries, service orders",
      },
    ],
  },
  {
    company: "Ebserh",
    role: "Full Stack Engineer",
    employmentType: "freelance",
    start: "2021-09",
    end: "2022-06",
    location: "Brasília-DF",
    stacks: [
      "Angular 12/13",
      "Angular Material 12",
      "Fuse (Angular Material template)",
      "Laravel 8",
      "PHP 7.4/8.0",
      "React 17",
      "TypeScript 4",
      "Transloco",
      "ng-apexcharts",
      "Tailwind CSS 2",
      "Eloquent (migrations, factories, API Resources)",
      "PostgreSQL 13",
      "Docker",
      "Portainer",
      "Azure Pipelines",
      "Git",
      "ESLint/Prettier/tsc",
      "Jest",
      "PHPUnit 9",
    ],
    projects: [
      {
        name: "Hospital management system",
        description:
          "Budget control and hospital/department registries for the federal university hospital network",
      },
    ],
  },
  {
    company: "Basis Tecnologia",
    role: "Full Stack Engineer",
    employmentType: "full-time",
    start: "2020-12",
    end: "2022-06",
    location: "Brasília-DF",
    stacks: [
      "React",
      "TypeScript",
      "Redux",
      "Context API",
      "MUI",
      "Styled Components",
      "Yup",
      "JWT + ACL",
      "SASS",
      "Jest",
      "PHP 7",
      "Laravel 8.1",
      "Eloquent",
      "Swagger",
      "AdonisJS",
      "Express",
      "Oracle",
      "Jenkins",
      "SonarQube",
      "Docker",
      "Docker Compose",
      "Rancher",
      "Harbor",
      "Adobe XD",
    ],
    projects: [
      {
        name: "SECIC",
        description: "Internal information classification system (federal government)",
      },
      {
        name: "Pátria Voluntária",
        description: "Donation collection and distribution platform (federal government program)",
      },
    ],
  },
  {
    company: "Partido Republicano da Ordem Social",
    role: "PHP Developer",
    employmentType: "freelance",
    start: "2017-11",
    end: "2020-12",
    location: "Brasília-DF",
    stacks: [
      "PHP 5.6/7.4",
      "Laravel",
      "Optimuz (in-house framework)",
      "Propel",
      "Eloquent",
      "Vue.js",
      "jQuery",
      "Bootstrap 4",
      "SASS/LESS",
      "MySQL",
      "PostgreSQL",
      "Redis",
      "Apache",
      "Linux",
    ],
    projects: [
      { name: "Gráfica Pros", description: "Print shop management and production" },
      { name: "SGP / SGJ / GPES", description: "Party, legal, and research management systems" },
    ],
  },
  {
    company: "Transoft",
    role: "PHP Developer",
    employmentType: "full-time",
    start: "2017-06",
    end: "2018-05",
    location: "Brasília-DF",
    stacks: ["PHP 4", "Oracle", "JavaScript", "HTML/CSS", "Bootstrap", "jQuery", "SASS"],
    projects: [
      { name: "Transnet", description: "Freight transportation and logistics management" },
    ],
  },
  {
    company: "Plug Digital",
    role: "Junior PHP Developer",
    employmentType: "full-time",
    start: "2016-01",
    end: "2017-11",
    location: "Brasília-DF",
    stacks: [
      "PHP 5.6",
      "MVC",
      "OOP",
      "Propel ORM",
      "In-house framework (CLI, industry-standard docs)",
      "PHPDoc/PSRs",
      "Bootstrap",
      "jQuery + plugins (datepicker, carousel, charts)",
      "SASS",
      "SVN",
      "Linux",
    ],
    projects: [
      { name: "ExpliQa", description: "Call center monitoring system" },
      { name: "SGP / GPES", description: "Party management and strategic research systems" },
    ],
  },
];
