import type { Experience } from "@/domain";

export const experiences: Experience[] = [
  {
    company: "G4F Soluções Corporativas",
    role: "Full Stack Developer",
    employmentType: "freelance",
    start: "2022-03",
    end: null,
    location: "Brasília-DF",
    stacks: [
      "Next.js 13/14",
      "React 17/18",
      "TypeScript",
      "MUI",
      "Redux",
      "React Query",
      "SWR",
      "NestJS 11",
      "Express",
      "AdonisJS",
      "Prisma 6",
      "Laravel",
      "Deno",
      "PostgreSQL",
      "Redis",
      "Docker",
      "Kubernetes",
      "gov.br SSO (Login Único/OIDC)",
      "Microservices",
      "WebSockets (socket.io)",
      "gov.br Design System (GOVBR-DS)",
      "Jenkins",
      "GitLab CI",
    ],
    projects: [
      {
        name: "Large-scale consular system (federal public sector)",
        description:
          "Worldwide multi-language public consular service, with document generation and identity verification",
      },
      { name: "E-folhas", description: "Payroll management for consulate staff" },
    ],
  },
  {
    company: "VegaIT",
    role: "Frontend Developer",
    employmentType: "part-time",
    start: "2022-08",
    end: "2024-05",
    stacks: ["React", "Redux", "TypeScript", "MSW", "Styled Components", "JWT", "Azure DevOps"],
    projects: [],
  },
  {
    company: "Ebserh",
    role: "Full Stack Developer",
    employmentType: "freelance",
    start: "2021-09",
    end: "2022-06",
    location: "Brasília-DF",
    stacks: ["PHP", "JavaScript"],
    projects: [],
  },
  {
    company: "Basis Tecnologia",
    role: "Full Stack Developer",
    employmentType: "full-time",
    start: "2020-12",
    end: "2022-06",
    stacks: [
      "React",
      "TypeScript",
      "Redux",
      "MUI",
      "Jest",
      "PHP 7",
      "Laravel 8.1",
      "Swagger",
      "AdonisJS",
      "Express",
      "Oracle",
      "Jenkins",
      "SonarQube",
      "Docker",
      "Rancher",
    ],
    projects: [
      { name: "SECIC", description: "Internal information classification system" },
      { name: "Pátria Voluntária", description: "Donation collection and distribution platform" },
    ],
  },
  {
    company: "Partido Republicano da Ordem Social",
    role: "PHP Developer",
    employmentType: "freelance",
    start: "2017-11",
    end: "2020-12",
    stacks: [
      "PHP 5.6/7.4",
      "Laravel",
      "Propel",
      "Eloquent",
      "Vue.js",
      "Bootstrap 4",
      "MySQL",
      "PostgreSQL",
      "Redis",
    ],
    projects: [
      { name: "Gráfica Pros", description: "Print shop management and production" },
      { name: "SGP / SGJ / GPES", description: "Party, legal, and research management systems" },
    ],
  },
  {
    company: "Transoft",
    role: "PHP Programmer",
    employmentType: "full-time",
    start: "2017-06",
    end: "2018-05",
    stacks: ["PHP 4", "Oracle", "Bootstrap", "jQuery", "SASS"],
    projects: [
      { name: "Transnet", description: "Freight transportation and logistics management" },
    ],
  },
  {
    company: "Plug Digital",
    role: "Junior PHP Programmer",
    employmentType: "full-time",
    start: "2016-01",
    end: "2017-11",
    stacks: ["PHP", "MVC", "POO", "Propel ORM", "SVN", "Linux"],
    projects: [{ name: "ExpliQa", description: "Call center monitoring system" }],
  },
];
