import type { Experience } from "@/domain";

export const experiences: Experience[] = [
  {
    company: "G4F Soluções Corporativas",
    role: "Full Stack Developer",
    employmentType: "freelance",
    start: "2022-03",
    end: null,
    location: "Brasília-DF",
    stacks: [
      "Next.js 15 (App Router/Turbopack)",
      "React 18",
      "TypeScript",
      "MUI 5",
      "Tailwind CSS",
      "Redux",
      "React Query",
      "SWR",
      "Formik/Yup",
      "Highcharts",
      "i18n (next-intl)",
      "NestJS 11",
      "Prisma 6",
      "Passport/JWT",
      "NestJS Throttler",
      "WebSockets (socket.io)",
      "Express",
      "AdonisJS",
      "Laravel",
      "Deno",
      "PostgreSQL",
      "Redis",
      "Docker",
      "Kubernetes",
      "Microsserviços",
      "SSO gov.br (Login Único/OIDC)",
      "Design System gov.br (GOVBR-DS)",
      "Jest",
      "SonarQube",
      "Jenkins",
      "GitLab CI",
    ],
    projects: [
      {
        name: "Sistema consular de grande porte (setor público federal)",
        description:
          "Atendimento consular ao público em todo o mundo, com suporte multi-idioma, geração documental e verificação de identidade",
      },
    ],
  },
  {
    company: "VegaIT",
    role: "Frontend Developer",
    employmentType: "part-time",
    start: "2022-08",
    end: "2024-05",
    stacks: [
      "React",
      "Redux",
      "Context API",
      "TypeScript",
      "MSW",
      "Styled Components",
      "JWT",
      "Azure DevOps",
    ],
    projects: [],
  },
  {
    company: "Ebserh",
    role: "Desenvolvedor Full Stack",
    employmentType: "freelance",
    start: "2021-09",
    end: "2022-06",
    location: "Brasília-DF",
    stacks: [],
    projects: [],
  },
  {
    company: "Basis Tecnologia",
    role: "Desenvolvedor Full Stack",
    employmentType: "full-time",
    start: "2020-12",
    end: "2022-06",
    stacks: [
      "React",
      "TypeScript",
      "Redux",
      "Context API",
      "MUI",
      "Styled Components",
      "Yup",
      "JWT + ACL",
      "SASS",
      "Jest",
      "PHP 7",
      "Laravel 8.1",
      "Eloquent",
      "Swagger",
      "AdonisJS",
      "Express",
      "Oracle",
      "Jenkins",
      "SonarQube",
      "Docker",
      "Docker Compose",
      "Rancher",
      "Adobe XD",
    ],
    projects: [
      { name: "SECIC", description: "Sistema interno de classificação de informações" },
      { name: "Pátria Voluntária", description: "Arrecadação e distribuição de doações" },
    ],
  },
  {
    company: "Partido Republicano da Ordem Social",
    role: "PHP Developer",
    employmentType: "freelance",
    start: "2017-11",
    end: "2020-12",
    stacks: [
      "PHP 5.6/7.4",
      "Laravel",
      "Optimuz (framework próprio)",
      "Propel",
      "Eloquent",
      "Vue.js",
      "jQuery",
      "Bootstrap 4",
      "SASS/LESS",
      "MySQL",
      "PostgreSQL",
      "Redis",
      "Apache",
      "Linux",
    ],
    projects: [
      { name: "Gráfica Pros", description: "Gestão e impressão de materiais gráficos" },
      {
        name: "SGP / SGJ / GPES",
        description: "Sistemas de gestão partidária, jurídica e de pesquisas",
      },
    ],
  },
  {
    company: "Transoft",
    role: "Programador PHP",
    employmentType: "full-time",
    start: "2017-06",
    end: "2018-05",
    stacks: ["PHP 4", "Oracle", "JavaScript", "HTML/CSS", "Bootstrap", "jQuery", "SASS"],
    projects: [{ name: "Transnet", description: "Gestão e logística de transportes" }],
  },
  {
    company: "Plug Digital",
    role: "Programador PHP Jr",
    employmentType: "full-time",
    start: "2016-01",
    end: "2017-11",
    stacks: [
      "PHP",
      "MVC",
      "POO",
      "Propel ORM",
      "PHPDoc/PSRs",
      "Bootstrap",
      "jQuery",
      "SASS",
      "SVN",
      "Linux",
    ],
    projects: [{ name: "ExpliQa", description: "Monitoramento de call center" }],
  },
];
