import type { Experience } from "@/domain";

export const experiences: Experience[] = [
  {
    company: "G4F Soluções Corporativas",
    role: "Full Stack Engineer",
    employmentType: "freelance",
    start: "2022-03",
    end: null,
    location: "Brasília-DF",
    stacks: [
      "Angular 22",
      "Angular Material + Fuse",
      "NestJS 11",
      "Laravel",
      "TypeScript",
      "Next.js 15 (App Router/Turbopack)",
      "React 18",
      "MUI 5",
      "Tailwind CSS",
      "Redux",
      "React Query",
      "SWR",
      "Formik/Yup",
      "Highcharts",
      "i18n (next-intl)",
      "Transloco",
      "ng-apexcharts",
      "Prisma 6",
      "Passport/JWT",
      "NestJS Throttler",
      "WebSockets (socket.io)",
      "Express",
      "AdonisJS",
      "Deno",
      "PostgreSQL",
      "Redis",
      "Docker",
      "Kubernetes",
      "Microsserviços",
      "SSO gov.br (Login Único/OIDC)",
      "Design System gov.br (GOVBR-DS)",
      "Jest",
      "SonarQube",
      "Jenkins",
      "GitLab CI",
      "hCaptcha + biometria facial",
      "DOMPurify",
      "CSP por request/HSTS",
      "Geração documental (PDF/xlsx)",
      "E-mail transacional (MJML)",
      "Bamboo",
      "Harbor",
    ],
    projects: [
      {
        name: "Sistema de atendimento ao público de grande porte (setor público federal)",
        description:
          "Plataforma multi-idioma de atendimento ao cidadão usada em mais de 90 unidades, com geração documental e verificação de identidade",
      },
      {
        name: "Nova geração do sistema de atendimento (setor público federal)",
        description:
          "Criação da versão modernizada que substituirá o sistema legado em uso em todas as unidades",
      },
    ],
    highlights: [
      "Engenheiro fundador do sistema de nova geração: autor do primeiro commit do back-end (NestJS) e do front-end (Next.js), e principal contribuidor dos dois repositórios até hoje.",
      "Construí o fluxo de requerimento de serviços de ponta a ponta (criação, combo de serviços, validação documental, histórico) e a fila de atendimento com tela de chamada em tempo real via WebSocket, com gateway autenticado por JWT e leitura em voz multilíngue.",
      "Conduzi auditoria de segurança da aplicação e sua remediação: verificação central de propriedade e de escopo por unidade para autorização em nível de objeto, guards de papéis default-deny, CSP, rate limiting, validação de upload por magic bytes e mascaramento de dados pessoais na auditoria.",
      "Projetei e construí a migração de dados legado → novo (MongoDB → PostgreSQL): extração paginada somente-leitura, cargas idempotentes e reversíveis com mapa de correlação e rollback, modo simulação, validada de ponta a ponta em sandbox.",
      "Autor do pipeline de CI/CD (Bitbucket Pipelines, SonarQube, Dependency-Track, imagens Docker no Harbor, deploy em Kubernetes para 4 ambientes) e dos gates locais de qualidade (Husky, lint-staged, SonarQube no pre-push, gate de cobertura).",
      "Mantenho o sistema legado em produção (Node.js, Express, MongoDB), uma instância por unidade em mais de 90 unidades: serviço de emissão de certificado com PDF, QR code e validação pública, correção de corrida no agendamento e reconexão de cursor com backoff exponencial após incidente em produção.",
      "Fluxo spec-driven com specs e planos versionados junto ao código, orquestração multiagente com saída validada por esquema e revisão adversarial, e um RAG interno de memória de engenharia (PostgreSQL + pgvector, busca híbrida, grafo de conhecimento) exposto por servidor MCP próprio.",
    ],
  },
  {
    company: "VegaIT",
    role: "Desenvolvedor Frontend",
    employmentType: "part-time",
    start: "2022-08",
    end: "2024-05",
    location: "Brasil",
    stacks: [
      "React",
      "Redux",
      "Context API",
      "React Query",
      "TypeScript",
      "MSW",
      "Styled Components",
      "JWT",
      "Azure DevOps (Pipelines)",
      "ESLint/Prettier/tsc",
    ],
    projects: [
      {
        name: "SIM – Manutenção",
        description:
          "Gestão de manutenção hoteleira: QR code de equipamentos, cadastros de andares, quartos e objetos, ordens de serviço",
      },
    ],
  },
  {
    company: "Ebserh",
    role: "Full Stack Engineer",
    employmentType: "freelance",
    start: "2021-09",
    end: "2022-06",
    location: "Brasília-DF",
    stacks: [
      "Angular 12/13",
      "Angular Material 12",
      "Fuse (Angular Material template)",
      "Laravel 8",
      "PHP 7.4/8.0",
      "React 17",
      "TypeScript 4",
      "Transloco",
      "ng-apexcharts",
      "Tailwind CSS 2",
      "Eloquent (migrations, factories, API Resources)",
      "PostgreSQL 13",
      "Docker",
      "Portainer",
      "Azure Pipelines",
      "Git",
      "ESLint/Prettier/tsc",
      "Jest",
      "PHPUnit 9",
    ],
    projects: [
      {
        name: "Sistema de gestão hospitalar",
        description:
          "Controle de orçamentos e cadastros de hospitais e setores para a rede de hospitais universitários federais",
      },
    ],
  },
  {
    company: "Basis Tecnologia",
    role: "Full Stack Engineer",
    employmentType: "full-time",
    start: "2020-12",
    end: "2022-06",
    location: "Brasília-DF",
    stacks: [
      "React",
      "TypeScript",
      "Redux",
      "Context API",
      "MUI",
      "Styled Components",
      "Yup",
      "JWT + ACL",
      "SASS",
      "Jest",
      "PHP 7",
      "Laravel 8.1",
      "Eloquent",
      "Swagger",
      "AdonisJS",
      "Express",
      "Oracle",
      "Jenkins",
      "SonarQube",
      "Docker",
      "Docker Compose",
      "Rancher",
      "Harbor",
      "Adobe XD",
    ],
    projects: [
      {
        name: "SECIC",
        description: "Sistema interno de classificação de informações (governo federal)",
      },
      {
        name: "Pátria Voluntária",
        description: "Arrecadação e distribuição de doações (programa do governo federal)",
      },
    ],
  },
  {
    company: "Partido Republicano da Ordem Social",
    role: "Desenvolvedor PHP",
    employmentType: "freelance",
    start: "2017-11",
    end: "2020-12",
    location: "Brasília-DF",
    stacks: [
      "PHP 5.6/7.4",
      "Laravel",
      "Optimuz (framework próprio)",
      "Propel",
      "Eloquent",
      "Vue.js",
      "jQuery",
      "Bootstrap 4",
      "SASS/LESS",
      "MySQL",
      "PostgreSQL",
      "Redis",
      "Apache",
      "Linux",
    ],
    projects: [
      { name: "Gráfica Pros", description: "Gestão e impressão de materiais gráficos" },
      {
        name: "SGP / SGJ / GPES",
        description: "Sistemas de gestão partidária, jurídica e de pesquisas",
      },
    ],
  },
  {
    company: "Transoft",
    role: "Desenvolvedor PHP",
    employmentType: "full-time",
    start: "2017-06",
    end: "2018-05",
    location: "Brasília-DF",
    stacks: ["PHP 4", "Oracle", "JavaScript", "HTML/CSS", "Bootstrap", "jQuery", "SASS"],
    projects: [{ name: "Transnet", description: "Gestão e logística de transportes" }],
  },
  {
    company: "Plug Digital",
    role: "Desenvolvedor PHP Jr",
    employmentType: "full-time",
    start: "2016-01",
    end: "2017-11",
    location: "Brasília-DF",
    stacks: [
      "PHP 5.6",
      "MVC",
      "POO",
      "Propel ORM",
      "Framework próprio (CLI, docs padrão de mercado)",
      "PHPDoc/PSRs",
      "Bootstrap",
      "jQuery + plugins (datepicker, carousel, gráficos)",
      "SASS",
      "SVN",
      "Linux",
    ],
    projects: [
      { name: "ExpliQa", description: "Monitoramento de call center" },
      { name: "SGP / GPES", description: "Gestão partidária e pesquisas estratégicas" },
    ],
  },
];
