import type { Experience } from "@/domain";

export const experiences: Experience[] = [
  {
    company: "G4F Soluções Corporativas",
    role: "Desenvolvedor Full Stack",
    employmentType: "freelance",
    start: "2022-03",
    end: null,
    location: "Brasília-DF",
    stacks: [
      "Next.js 15 (App Router/Turbopack)",
      "React 18",
      "TypeScript",
      "MUI 5",
      "Tailwind CSS",
      "Redux",
      "React Query",
      "SWR",
      "Formik/Yup",
      "Highcharts",
      "i18n (next-intl)",
      "NestJS 11",
      "Prisma 6",
      "Passport/JWT",
      "NestJS Throttler",
      "WebSockets (socket.io)",
      "Express",
      "AdonisJS",
      "Laravel",
      "Deno",
      "PostgreSQL",
      "Redis",
      "Docker",
      "Kubernetes",
      "Microsserviços",
      "SSO gov.br (Login Único/OIDC)",
      "Design System gov.br (GOVBR-DS)",
      "Jest",
      "SonarQube",
      "Jenkins",
      "GitLab CI",
      "hCaptcha + biometria facial",
      "DOMPurify",
      "CSP por request/HSTS",
      "Geração documental (PDF/xlsx)",
      "E-mail transacional (MJML)",
      "Bamboo",
      "Harbor",
    ],
    projects: [
      {
        name: "Sistema consular de grande porte (setor público federal)",
        description:
          "Atendimento consular ao público em todo o mundo, com suporte multi-idioma, geração documental e verificação de identidade",
      },
      {
        name: "Sistema de folha de pagamento consular (setor público federal)",
        description: "Gestão da folha de pagamento de funcionários dos consulados no exterior",
      },
    ],
  },
  {
    company: "VegaIT",
    role: "Desenvolvedor Frontend",
    employmentType: "part-time",
    start: "2022-08",
    end: "2024-05",
    location: "Brasil",
    stacks: [
      "React",
      "Redux",
      "Context API",
      "React Query",
      "TypeScript",
      "MSW",
      "Styled Components",
      "JWT",
      "Azure DevOps (Pipelines)",
      "ESLint/Prettier/tsc",
    ],
    projects: [
      {
        name: "SIM – Manutenção",
        description:
          "Gestão de manutenção hoteleira: QR code de equipamentos, cadastros de andares, quartos e objetos, ordens de serviço",
      },
    ],
  },
  {
    company: "Ebserh",
    role: "Desenvolvedor Full Stack",
    employmentType: "freelance",
    start: "2021-09",
    end: "2022-06",
    location: "Brasília-DF",
    stacks: [
      "React 17",
      "TypeScript 4",
      "Laravel 8",
      "PHP 7.4/8.0",
      "Eloquent (migrations, factories, API Resources)",
      "PostgreSQL 13",
      "Docker",
      "Portainer",
      "Azure Pipelines",
      "Git",
      "ESLint/Prettier/tsc",
      "Jest",
      "PHPUnit 9",
    ],
    projects: [
      {
        name: "Sistema de gestão hospitalar",
        description:
          "Controle de orçamentos e cadastros de hospitais e setores para a rede de hospitais universitários federais",
      },
    ],
  },
  {
    company: "Basis Tecnologia",
    role: "Desenvolvedor Full Stack",
    employmentType: "full-time",
    start: "2020-12",
    end: "2022-06",
    location: "Brasília-DF",
    stacks: [
      "React",
      "TypeScript",
      "Redux",
      "Context API",
      "MUI",
      "Styled Components",
      "Yup",
      "JWT + ACL",
      "SASS",
      "Jest",
      "PHP 7",
      "Laravel 8.1",
      "Eloquent",
      "Swagger",
      "AdonisJS",
      "Express",
      "Oracle",
      "Jenkins",
      "SonarQube",
      "Docker",
      "Docker Compose",
      "Rancher",
      "Harbor",
      "Adobe XD",
    ],
    projects: [
      {
        name: "SECIC",
        description: "Sistema interno de classificação de informações (governo federal)",
      },
      {
        name: "Pátria Voluntária",
        description: "Arrecadação e distribuição de doações (programa do governo federal)",
      },
    ],
  },
  {
    company: "Partido Republicano da Ordem Social",
    role: "Desenvolvedor PHP",
    employmentType: "freelance",
    start: "2017-11",
    end: "2020-12",
    location: "Brasília-DF",
    stacks: [
      "PHP 5.6/7.4",
      "Laravel",
      "Optimuz (framework próprio)",
      "Propel",
      "Eloquent",
      "Vue.js",
      "jQuery",
      "Bootstrap 4",
      "SASS/LESS",
      "MySQL",
      "PostgreSQL",
      "Redis",
      "Apache",
      "Linux",
    ],
    projects: [
      { name: "Gráfica Pros", description: "Gestão e impressão de materiais gráficos" },
      {
        name: "SGP / SGJ / GPES",
        description: "Sistemas de gestão partidária, jurídica e de pesquisas",
      },
    ],
  },
  {
    company: "Transoft",
    role: "Desenvolvedor PHP",
    employmentType: "full-time",
    start: "2017-06",
    end: "2018-05",
    location: "Brasília-DF",
    stacks: ["PHP 4", "Oracle", "JavaScript", "HTML/CSS", "Bootstrap", "jQuery", "SASS"],
    projects: [{ name: "Transnet", description: "Gestão e logística de transportes" }],
  },
  {
    company: "Plug Digital",
    role: "Desenvolvedor PHP Jr",
    employmentType: "full-time",
    start: "2016-01",
    end: "2017-11",
    location: "Brasília-DF",
    stacks: [
      "PHP 5.6",
      "MVC",
      "POO",
      "Propel ORM",
      "Framework próprio (CLI, docs padrão de mercado)",
      "PHPDoc/PSRs",
      "Bootstrap",
      "jQuery + plugins (datepicker, carousel, gráficos)",
      "SASS",
      "SVN",
      "Linux",
    ],
    projects: [
      { name: "ExpliQa", description: "Monitoramento de call center" },
      { name: "SGP / GPES", description: "Gestão partidária e pesquisas estratégicas" },
    ],
  },
];
